### ISSUE TITLE
Error adding workshop collection ID to Workshop maps for server

### ISSUE THREAD

**Issue by gitrummy** [fpaezf/Counter-Strike-dedicated-server-admin-tool#6]
![image](https://github.com/user-attachments/assets/d66c902a-78ce-495a-b8df-7dd528182e9b)

Workshop ID used - 2837257027

**Comment by fpaezf** [comment]
You need a web api key: https://steamcommunity.com/dev/apikey
Once generated, put it on application settings window.

![Sin título](https://github.com/user-attachments/assets/97353da5-f6ae-485b-95df-ba5afe52b1b7)
